#!/usr/bin/env node
/**
 * Self-hosts the two Google fonts the design calls for, so the production site
 * makes no third-party font requests.
 *
 * Downloads the woff2 files for the latin and latin-ext subsets only, writes
 * them to public/fonts/, and generates src/styles/fonts.css with @font-face
 * rules (font-display: swap) pointing at the local copies.
 *
 * Run once (or when the font selection changes): npm run fonts
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const FONT_DIR = path.join(root, 'public', 'fonts');
const CSS_OUT = path.join(root, 'src', 'styles', 'fonts.css');

const GOOGLE_CSS =
  'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;1,300;1,400&family=Jost:wght@300;400;500&display=swap';

// woff2 needs a modern-browser UA or Google serves the ttf fallback.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

/** Splits the stylesheet into `{ subset, block }` records. */
function parseBlocks(css) {
  const blocks = [];
  const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/gi;
  let match;
  while ((match = re.exec(css))) {
    blocks.push({ subset: match[1], block: match[2] });
  }
  return blocks;
}

function fieldOf(block, name) {
  return new RegExp(`${name}:\\s*([^;]+);`).exec(block)?.[1].trim() ?? '';
}

function fileNameFor(block, subset) {
  const family = fieldOf(block, 'font-family').replace(/['"]/g, '');
  const weight = fieldOf(block, 'font-weight');
  const style = fieldOf(block, 'font-style');
  const slug = family.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  return `${slug}-${weight}${style === 'italic' ? '-italic' : ''}-${subset}.woff2`;
}

async function main() {
  await fs.mkdir(FONT_DIR, { recursive: true });
  await fs.mkdir(path.dirname(CSS_OUT), { recursive: true });

  const res = await fetch(GOOGLE_CSS, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`Google Fonts responded ${res.status}`);
  const css = await res.text();

  const rules = [];
  for (const { subset, block } of parseBlocks(css)) {
    if (!KEEP_SUBSETS.has(subset)) continue;

    const url = /url\((https:\/\/[^)]+)\)/.exec(block)?.[1];
    if (!url) continue;

    const fileName = fileNameFor(block, subset);
    const bytes = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
    await fs.writeFile(path.join(FONT_DIR, fileName), bytes);

    rules.push(
      block
        .replace(/url\(https:\/\/[^)]+\)/, `url('/fonts/${fileName}')`)
        .replace(/@font-face\s*\{/, '@font-face {')
    );
    console.log(`  ✓ ${fileName}  ${(bytes.length / 1024).toFixed(1)} kB`);
  }

  const header = `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.
   Self-hosted Cormorant Garamond + Jost, latin and latin-ext subsets. */\n\n`;
  await fs.writeFile(CSS_OUT, header + rules.join('\n\n') + '\n');
  console.log(`\nWrote ${rules.length} @font-face rules to src/styles/fonts.css`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
